import { router, publicProcedure, protectedProcedure } from '../trpc'
import { z } from "zod";


export const characterRouter = router({
  getAll: publicProcedure
  .query(async({ ctx })=>{
    try {
      return await ctx.prisma.charSheet.findMany({
        select: {
          PlayerName: true,
          CharName:  true,
          CharRace:  true,
          CharClass: true,
          CharBackground:true,
          CharAlignment: true,
          CharInitiative:true,
          CharSpeed: true,
          CharProficiency:true,
          CharInspiration:true,
          CharStrength:  true,
          StrengthSaving:true,
          StrengthAthLetics:true,
          CharDexterity: true,
          DexteritySaving:  true,
          DexterityAcrobatics:true,
          DexteritySleight: true,
          DexterityStealth: true,
          CharConstitution:true,
          ConstitutionSaving: true,
          CharIntelligence:true,
          IntelligenceSaving: true,
          IntelligenceArcana: true,
          IntelligenceHistory:true,
          IntelligenceInvestigate:true,
          IntelligenceNature: true,
          IntelligenceReligion:   true,
          CharWisdom:true,
          WisdomSaving:  true,
          WisdomAnimal:  true,
          WisdomInsight: true,
          WisdomMedicine:true,
          WisdomPerception: true,
          WisdomSurvival:true,
          PassiveWisdom: true,
          CharCharisma:  true,
          CharismaSaving:true,
          CharismaDeception:true,
          CharismaIntimidation:   true,
          CharismaPerformance:true,
          CharismaPersuasion: true,
          Treasures: true,
          CharArmorClass:true,
          CharHitPoints: true,
          CharLevel: true,
          CharAge:   true,
          CharHeight:true,
          CharWeight:true,
          CharVision:true,
          CharSkin:  true,
          CharHair:  true,
          CharEyes:  true,
          CharReputation:true,
          CharPersonality:true,
          CharIdeals:true,
          CharBonds:true,
          CharFlaws: true,
          CharAttacksSpellNames1:true,
          CharAttacksSpellAttack1:true,
          CharAttacksSpellDamage1:true,
          CharAttacksSpellRange1:true,
          CharAttacksSpellAmmo1: true,
          CharAttacksSpellUsed1: true,
          CharAttacksSpellNames2:true,
          CharAttacksSpellAttack2:true,
          CharAttacksSpellDamage2:true,
          CharAttacksSpellRange2:true,
          CharAttacksSpellAmmo2: true,
          CharAttacksSpellUsed2: true,
          CharAttacksSpellNames3:true,
          CharAttacksSpellAttack3:true,
          CharAttacksSpellDamage3:true,
          CharAttacksSpellRange3:true,
          CharAttacksSpellAmmo3: true,
          CharAttacksSpellUsed3: true,
          CharAttacksSpellNames4:true,
          CharAttacksSpellAttack4:true,
          CharAttacksSpellDamage4:true,
          CharAttacksSpellRange4:true,
          CharAttacksSpellAmmo4: true,
          CharAttacksSpellUsed4: true,
          CharAttacksSpellNames5:true,
          CharAttacksSpellAttack5:true,
          CharAttacksSpellDamage5:true,
          CharAttacksSpellRange5:true,
          CharAttacksSpellAmmo5: true,
          CharAttacksSpellUsed5: true,
          CharAttacksSpellNames6:true,
          CharAttacksSpellAttack6:true,
          CharAttacksSpellDamage6:true,
          CharAttacksSpellRange6:true,
          CharAttacksSpellAmmo6: true,
          CharAttacksSpellUsed6: true,
          CharSpecialAbilities:  true,
          CharProficienciesLang: true,
          CharNotesEquipment:    true,
        },
        orderBy: {
          createdAt: "desc",
        },
      });
    } catch (error) {
      console.log('Error', error)
    }
  }),
  postMessage: protectedProcedure
  .input(
    z.object({
      PlayerName: z.string(),
      CharName:  z.string(),
      CharRace:  z.string(),
      CharClass: z.string(),
      CharBackground:z.string(),
      CharAlignment: z.string(),
      CharInitiative:z.string(),
      CharSpeed: z.string(),
      CharProficiency:z.string(),
      CharInspiration:z.string(),
      CharStrength:  z.string(),
      StrengthSaving:z.boolean(),
      StrengthAthLetics:z.boolean(),
      CharDexterity: z.string(),
      DexteritySaving:  z.boolean(),
      DexterityAcrobatics:z.boolean(),
      DexteritySleight: z.boolean(),
      DexterityStealth: z.boolean(),
      CharConstitution:z.string(),
      ConstitutionSaving: z.boolean(),
      CharIntelligence:z.string(),
      IntelligenceSaving: z.boolean(),
      IntelligenceArcana: z.boolean(),
      IntelligenceHistory:z.boolean(),
      IntelligenceInvestigate:z.boolean(),
      IntelligenceNature: z.boolean(),
      IntelligenceReligion:   z.boolean(),
      CharWisdom:z.string(),
      WisdomSaving:  z.boolean(),
      WisdomAnimal:  z.boolean(),
      WisdomInsight: z.boolean(),
      WisdomMedicine:z.boolean(),
      WisdomPerception: z.boolean(),
      WisdomSurvival:z.boolean(),
      PassiveWisdom: z.string(),
      CharCharisma:  z.string(),
      CharismaSaving:z.boolean(),
      CharismaDeception:z.boolean(),
      CharismaIntimidation:   z.boolean(),
      CharismaPerformance:z.boolean(),
      CharismaPersuasion: z.boolean(),
      Treasures: z.string(),
      CharArmorClass:z.string(),
      CharHitPoints: z.string(),
      CharLevel: z.string(),
      CharAge:   z.string(),
      CharHeight:z.string(),
      CharWeight:z.string(),
      CharVision:z.string(),
      CharSkin:  z.string(),
      CharHair:  z.string(),
      CharEyes:  z.string(),
      CharReputation:z.string(),
      CharPersonality:z.string(),
      CharIdeals:z.string(),
      CharBonds:z.string(),
      CharFlaws: z.string(),
      CharAttacksSpellNames1:z.string(),
      CharAttacksSpellAttack1:z.string(),
      CharAttacksSpellDamage1:z.string(),
      CharAttacksSpellRange1:z.string(),
      CharAttacksSpellAmmo1: z.string(),
      CharAttacksSpellUsed1: z.string(),
      CharAttacksSpellNames2:z.string(),
      CharAttacksSpellAttack2:z.string(),
      CharAttacksSpellDamage2:z.string(),
      CharAttacksSpellRange2:z.string(),
      CharAttacksSpellAmmo2: z.string(),
      CharAttacksSpellUsed2: z.string(),
      CharAttacksSpellNames3:z.string(),
      CharAttacksSpellAttack3:z.string(),
      CharAttacksSpellDamage3:z.string(),
      CharAttacksSpellRange3:z.string(),
      CharAttacksSpellAmmo3: z.string(),
      CharAttacksSpellUsed3: z.string(),
      CharAttacksSpellNames4:z.string(),
      CharAttacksSpellAttack4:z.string(),
      CharAttacksSpellDamage4:z.string(),
      CharAttacksSpellRange4:z.string(),
      CharAttacksSpellAmmo4: z.string(),
      CharAttacksSpellUsed4: z.string(),
      CharAttacksSpellNames5:z.string(),
      CharAttacksSpellAttack5:z.string(),
      CharAttacksSpellDamage5:z.string(),
      CharAttacksSpellRange5:z.string(),
      CharAttacksSpellAmmo5: z.string(),
      CharAttacksSpellUsed5: z.string(),
      CharAttacksSpellNames6:z.string(),
      CharAttacksSpellAttack6:z.string(),
      CharAttacksSpellDamage6:z.string(),
      CharAttacksSpellRange6:z.string(),
      CharAttacksSpellAmmo6: z.string(),
      CharAttacksSpellUsed6: z.string(),
      CharSpecialAbilities:  z.string(),
      CharProficienciesLang: z.string(),
      CharNotesEquipment:    z.string(),
  }),
  )
  .mutation(async ({ ctx, input }) => {
    try {
      await ctx.prisma.charSheet.create({
        data: {
          PlayerName: input.PlayerName,
          CharName: input.CharName,
          CharRace: input.CharRace,
          CharClass: input.CharClass,
          CharBackground: input.CharBackground,
          CharAlignment: input.CharAlignment,
          CharInitiative: input.CharInitiative,
          CharSpeed: input.CharSpeed,
          CharProficiency: input.CharProficiency,
          CharInspiration: input.CharInspiration,
          CharStrength: input.CharStrength,
          StrengthSaving: input.StrengthSaving,
          StrengthAthLetics: input.StrengthAthLetics,
          CharDexterity: input.CharDexterity,
          DexteritySaving: input.DexteritySaving,
          DexterityAcrobatics: input.DexterityAcrobatics,
          DexteritySleight: input.DexteritySleight,
          DexterityStealth: input.DexterityStealth,
          CharConstitution: input.CharConstitution,
          ConstitutionSaving: input.ConstitutionSaving,
          CharIntelligence: input.CharIntelligence,
          IntelligenceSaving: input.IntelligenceSaving,
          IntelligenceArcana: input.IntelligenceArcana,
          IntelligenceHistory: input.IntelligenceHistory,
          IntelligenceInvestigate: input.IntelligenceInvestigate,
          IntelligenceNature: input.IntelligenceNature,
          IntelligenceReligion: input.IntelligenceReligion,
          CharWisdom: input.CharWisdom,
          WisdomSaving: input.WisdomSaving,
          WisdomAnimal: input.WisdomAnimal,
          WisdomInsight: input.WisdomInsight,
          WisdomMedicine: input.WisdomMedicine,
          WisdomPerception: input.WisdomPerception,
          WisdomSurvival: input.WisdomSurvival,
          PassiveWisdom: input.PassiveWisdom,
          CharCharisma: input.CharCharisma,
          CharismaSaving: input.CharismaSaving,
          CharismaDeception: input.CharismaDeception,
          CharismaIntimidation: input.CharismaIntimidation,
          CharismaPerformance: input.CharismaPerformance,
          CharismaPersuasion: input.CharismaPersuasion,
          Treasures: input.Treasures,
          CharArmorClass: input.CharArmorClass,
          CharHitPoints: input.CharHitPoints,
          CharLevel: input.CharLevel,
          CharAge: input.CharAge,
          CharHeight: input.CharHeight,
          CharWeight: input.CharWeight,
          CharVision: input.CharVision,
          CharSkin: input.CharSkin,
          CharHair: input.CharHair,
          CharEyes: input.CharEyes,
          CharReputation: input.CharReputation,
          CharPersonality: input.CharPersonality,
          CharIdeals: input.CharIdeals,
          CharBonds: input.CharBonds,
          CharFlaws: input.CharFlaws,
          CharAttacksSpellNames1: input.CharAttacksSpellNames1,
          CharAttacksSpellAttack1: input.CharAttacksSpellAttack1,
          CharAttacksSpellDamage1: input.CharAttacksSpellDamage1,
          CharAttacksSpellRange1: input.CharAttacksSpellRange1,
          CharAttacksSpellAmmo1: input.CharAttacksSpellAmmo1,
          CharAttacksSpellUsed1: input.CharAttacksSpellUsed1,
          CharAttacksSpellNames2: input.CharAttacksSpellNames2,
          CharAttacksSpellAttack2: input.CharAttacksSpellAttack2,
          CharAttacksSpellDamage2: input.CharAttacksSpellDamage2,
          CharAttacksSpellRange2: input.CharAttacksSpellRange2,
          CharAttacksSpellAmmo2: input.CharAttacksSpellAmmo2,
          CharAttacksSpellUsed2: input.CharAttacksSpellUsed2,
          CharAttacksSpellNames3: input.CharAttacksSpellNames3,
          CharAttacksSpellAttack3: input.CharAttacksSpellAttack3,
          CharAttacksSpellDamage3: input.CharAttacksSpellDamage3,
          CharAttacksSpellRange3: input.CharAttacksSpellRange3,
          CharAttacksSpellAmmo3: input.CharAttacksSpellAmmo3,
          CharAttacksSpellUsed3: input.CharAttacksSpellUsed3,
          CharAttacksSpellNames4: input.CharAttacksSpellNames4,
          CharAttacksSpellAttack4: input.CharAttacksSpellAttack4,
          CharAttacksSpellDamage4: input.CharAttacksSpellDamage4,
          CharAttacksSpellRange4: input.CharAttacksSpellRange4,
          CharAttacksSpellAmmo4: input.CharAttacksSpellAmmo4,
          CharAttacksSpellUsed4: input.CharAttacksSpellUsed4,
          CharAttacksSpellNames5: input.CharAttacksSpellNames5,
          CharAttacksSpellAttack5: input.CharAttacksSpellAttack5,
          CharAttacksSpellDamage5: input.CharAttacksSpellDamage5,
          CharAttacksSpellRange5: input.CharAttacksSpellRange5,
          CharAttacksSpellAmmo5: input.CharAttacksSpellAmmo5,
          CharAttacksSpellUsed5: input.CharAttacksSpellUsed5,
          CharAttacksSpellNames6: input.CharAttacksSpellNames6,
          CharAttacksSpellAttack6: input.CharAttacksSpellAttack6,
          CharAttacksSpellDamage6: input.CharAttacksSpellDamage6,
          CharAttacksSpellRange6: input.CharAttacksSpellRange6,
          CharAttacksSpellAmmo6: input.CharAttacksSpellAmmo6,
          CharAttacksSpellUsed6: input.CharAttacksSpellUsed6,
          CharSpecialAbilities: input.CharSpecialAbilities,
          CharProficienciesLang: input.CharProficienciesLang,
          CharNotesEquipment: input.CharNotesEquipment,
        },
      });
    } catch (error){
      console.log(error)
    }
  }),
})
  